apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-issuer
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: gabriel.rodrigues@vocon-it.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cloudflare-staging-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          email: gabriel.rodrigues@vocon-it.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
